export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const ADD_TO_CART = "ADD_TO_CART";
export const HANDLE_DIRECTION = "HANDLE_DIRECTION";
export const HANDLE_CHECKBOX_VALUE = "HANDLE_CHECKBOX_VALUE";
export const CALCULATE_ORDER = "CALCULATE_ORDER";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const HANDLE_PRODUCT_AMOUNT = "HANDLE_PRODUCT_AMOUNT"
export const CLEAR_CART = "CLEAR_CART";

export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const SHOW_DETAILS = "SHOW_DETAILS";
