//UI
export const SET_CUR_PAGE = "SET_CUR_PAGE";
export const SET_DRAWER_OPEN = "SET_DRAWER_OPEN";
export const SET_DRAWER_CLOSE = "SET_DRAWER_CLOSE";
export const SET_FILTER_TOGGLE = "SET_FILTER_TOGGLE";
export const SET_INVERTED_COLOR = "SET_INVERTED_COLOR";
export const SORT_FILTER_VALUE = "SORT_FILTER_VALUE";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const TOGGLE_CART_HIDDEN = "TOGGLE_CART_HIDDEN";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const CLEAR_ITEM_FORM_CART = "CLEAR_ITEM_FORM_CART";
export const UPDATE_COLLECTIONS = "UPDATE_COLLECTIONS";